"""
FastAPI app. Each route here corresponds to one entry in the
"ENDPOINT CONTRACT" comment at the top of src/api/client.js in the
frontend — path, method, and response shape are matched deliberately.

Run with:  uvicorn main:app --reload --port 8000
Docs at:   http://localhost:8000/docs  (auto-generated by FastAPI —
           useful for testing a route by hand before the frontend calls it)
"""

from datetime import datetime

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

import db
import detection
from billing import calculate_bill_amount
from schemas import EntryPayload, ExitPayload, VehiclePayload

app = FastAPI(title="Gatehouse Parking API")

# The Vite dev server runs on :5173 and is a different origin from :8000,
# so the browser blocks the frontend's fetch() calls unless we explicitly
# allow it here. In production, tighten allow_origins to your real domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Wings
# ---------------------------------------------------------------------------

@app.get("/api/wings")
def get_wings():
    return db.list_wings()


@app.get("/api/wings/{wing}/centre")
def get_centre(wing: str):
    centre_id = db.get_centre_for_wing(wing)
    if centre_id is None:
        raise HTTPException(status_code=404, detail=f"No centre found for wing '{wing}'")
    return {"centre_id": centre_id}


# ---------------------------------------------------------------------------
# Spot availability
# ---------------------------------------------------------------------------

@app.get("/api/spots/availability")
def get_spot_availability(wing: str):
    return db.get_spot_availability(wing)


@app.get("/api/spots")
def get_available_spots(wing: str, centre_id: int, size: str):
    return db.get_available_spots(wing, centre_id, size)


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------

@app.post("/api/detection/start")
def start_detection():
    detection.start_detection()
    return {"ok": True}


@app.get("/api/detection/status")
def detection_status():
    return detection.get_status()


@app.post("/api/detection/stop")
def stop_detection():
    detection.stop_detection()
    return {"ok": True}


# ---------------------------------------------------------------------------
# Vehicles / owners
# ---------------------------------------------------------------------------

@app.get("/api/vehicles/{license_plate}")
def get_vehicle(license_plate: str):
    vehicle = db.get_vehicle(license_plate)
    if vehicle is None:
        raise HTTPException(status_code=404, detail="No vehicle found for that plate")
    return vehicle


@app.post("/api/vehicles")
def save_vehicle(payload: VehiclePayload):
    db.save_vehicle(
        owner_id=payload.owner_id,
        license_plate=payload.license_plate,
        model=payload.model,
        colour=payload.colour,
        vehicle_type=payload.type,
        phone=payload.phone,
        name=payload.name,
    )
    return {"ok": True}


# ---------------------------------------------------------------------------
# Entry / exit
# ---------------------------------------------------------------------------

@app.post("/api/entries")
def mark_entry(payload: EntryPayload):
    db.mark_entry(
        entry_time=datetime.now(),
        license_plate=payload.license_plate,
        centre_id=payload.centre_id,
        wing=payload.wing,
        floor=payload.floor,
        spot_number=payload.spot_number,
        folder_path=payload.folder_path or "",
    )
    return {"ok": True}


@app.post("/api/exits")
def mark_exit(payload: ExitPayload):
    session = db.get_active_session(payload.license_plate)
    if session is None:
        raise HTTPException(
            status_code=404, detail="No active parking session found for this plate"
        )

    vehicle_type = db.get_vehicle_type(payload.license_plate) or "Two Wheeler"

    exit_time = datetime.now()
    entry_time = session["entry_time"]
    duration = exit_time - entry_time
    amount = calculate_bill_amount(duration.total_seconds(), vehicle_type)

    db.record_exit(
        entry_time=entry_time,
        exit_time=exit_time,
        duration=duration,
        amount=amount,
        centre_id=session["centre_id"],
        wing=session["wing"],
        floor=session["floor"],
        spot_number=session["spot_number"],
    )

    return {
        "entry_time": entry_time.isoformat(),
        "exit_time": exit_time.isoformat(),
        "duration": str(duration),
        "amount": amount,
    }


# ---------------------------------------------------------------------------
# Billing
# ---------------------------------------------------------------------------

@app.get("/api/bills/{license_plate}/latest")
def get_latest_bill(license_plate: str):
    bill = db.get_latest_bill(license_plate)
    if bill is None:
        raise HTTPException(status_code=404, detail="No completed session found for this plate")
    return {
        "entry_time": bill["entry_time"].strftime("%Y-%m-%d %H:%M:%S"),
        "exit_time": bill["exit_time"].strftime("%Y-%m-%d %H:%M:%S"),
        "duration": str(bill["duration"]),
        "amount": bill["amount"],
        "owner_name": bill["owner_name"],
    }
